# fly.toml app configuration file generated for patxi-arana-storydots on 2023-05-04T18:11:43-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patxi-arana-storydots"
primary_region = "scl"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
